export const theme = {
  colors: {
    primary: "#262626",
    // secondary: "#FFF5DB",
    // success: "#4caf50",
    // danger: "#ff5722",
    // warning: "#ffeb3b",
    // info: "#00bcd4",
    // light: "#f0f0f0",
    // dark: "#333333",
    // prueba: "#F7E018",
    // pruebaDos: "#FFFF00",
    text: {
      primary: "hsl(0, 0%, 15%)",
      subPrimary: "hsl(0, 0%, 54%)",
      // secondary: "hsl(44, 100%, 93%)",
      // subSecondary: "hsl(44, 100%, 100%)",
      // primary: "hsla(0, 0%, 14.50%, 1)",
      // secondary: "hsla(44, 100%, 92.70%, 1)",
      // subPrimary: "hsla(0, 0%, 14.50%, 0.7)",
      // subSecondary: "hsla(44, 100%, 92.70%, 0.7)",
    },
    background: {
      light: "#FFF5DB",
      // dark: "#262626",
      // default: "#f0f0f0",
      // paper: "#ffffff",
      // primary: "#4caf50",
      // secondary: "#ff5722",
    },
    boxShadow: {
      primary: "hsla(0, 0%, 0%, 0.08)",
    },
    // border: "#262626",
  },
  spacing: {
    // xsmall: ".25rem",
    // small: ".5rem",
    medium: "1rem",
    large: "1.5rem",
    // xlarge: "2rem",
    xxlarge: "3rem",
    header: "4rem",
  },
  padding: {
    xsmall: ".25rem",
    small: ".5rem",
    medium: "1rem",
    large: "1.5rem",
    // xlarge: "2rem",
    // xxlarge: "3rem",
  },
  borderRadius: {
    // small: "2px",
    medium: "5px",
    // large: "8px",
    // xlarge: "16px",
  },
  zIndex: {
    fixed: 1000,
  },
  breakpoints: {
    // mobile: "36rem",
    // tablet: "48rem",
    // laptop: "62rem",
    desktop: "70rem",
  },
  fonts: {
    primary: "Whyte",
    secondary: "Apercu Mono",
    tertiary: "Playfair Display",
  },
  fontSizes: {
    // xsmall: ".625rem",
    small: ".75rem",
    medium: "1rem",
    // large: "1.5rem",
    // xlarge: "2rem",
    // xxlarge: "4rem",
  },
  lineHeights: {
    // small: 1.0,
    // medium: 1.3,
    // large: 1.6,
  },
  letterSpacings: {
    small: ".0625rem",
    medium: ".125rem",
    // large: ".25rem",
    // large: "1rem",
  },
};
