export const theme = {
  colors: {
    primary: "#FFFF00",
    // secondary: "#ff5722",
    // success: "#4caf50",
    // danger: "#ff5722",
    // warning: "#ffeb3b",
    // info: "#00bcd4",
    // light: "#f0f0f0",
    // dark: "#333333",
    prueba: "#F7E018",
    pruebaDos: "#FFFF00",
    text: {
      primary: "#252525",
      // secondary: "#757575",
      // light: "#ffffff",
    },
    background: {
      // default: "#f0f0f0",
      // paper: "#ffffff",
      // primary: "#4caf50",
      // secondary: "#ff5722",
      light: "#FFF5DA",
      dark: "#333333",
    },
    border: "#e0e0e0",
  },
  spacing: {
    xsmall: ".25rem",
    small: ".5rem",
    medium: "1rem",
    large: "1.5rem",
    xlarge: "2rem",
    xxlarge: "3rem",
    header: "4rem",
  },
  padding: {
    xsmall: ".25rem",
    small: ".5rem",
    medium: "1rem",
    large: "1.5rem",
    xlarge: "2rem",
    xxlarge: "3rem",
  },
  borderRadius: {
    small: "2px",
    medium: "4px",
    large: "8px",
    xlarge: "16px",
  },
  zIndex: {
    dropdown: 1000,
    sticky: 1020,
    fixed: 1030,
    backdrop: 1040,
    modal: 1050,
    popover: 1060,
    tooltip: 1070,
  },
  breakpoints: {
    mobile: "36rem",
    tablet: "48rem",
    laptop: "62rem",
    desktop: "75rem",
  },
  fontSizes: {
    xsmall: ".625rem",
    small: ".75rem",
    medium: "1rem",
    large: "1.5rem",
    xlarge: "2rem",
    xxlarge: "3rem",
  },
  fonts: {
    primary: "Whyte",
    secondary: "Apercu Mono",
  },
};
