export const theme = {
  colors: {
    primary: "#4caf50",
    secondary: "#ff5722",
    success: "#4caf50",
    danger: "#ff5722",
    warning: "#ffeb3b",
    info: "#00bcd4",
    light: "#f0f0f0",
    dark: "#333333",
    text: {
      primary: "#333333",
      secondary: "#757575",
      light: "#ffffff",
    },
    background: {
      default: "#f0f0f0",
      paper: "#ffffff",
      primary: "#4caf50",
      secondary: "#ff5722",
      light: "#f0f0f0",
      dark: "#333333",
    },
    border: "#e0e0e0",
  },
  fontSizes: {
    xsmall: ".625rem",
    small: ".75rem",
    medium: "1rem",
    large: "1.5rem",
    xlarge: "2rem",
    xxlarge: "3rem",
  },
  spacing: {
    xsmall: ".25rem",
    small: ".5rem",
    medium: "1rem",
    large: "1.5rem",
    xlarge: "2rem",
  },
  borderRadius: {
    small: "2px",
    medium: "4px",
    large: "8px",
  },
};
